version: "3.8"

services:
  postgres:
    image: postgres:15
    container_name: litellm_postgres
    restart: always
    environment:
      POSTGRES_USER: litellm
      POSTGRES_PASSWORD: litellm
      POSTGRES_DB: litellm
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U litellm -d litellm"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: litellm_redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    command: redis-server --appendonly yes

  litellm:
    image: ghcr.io/berriai/litellm:v1.77.3-stable
    container_name: litellm
    platform: linux/amd64
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ./litellm_config.yaml:/app/config.yaml
      - ./service_account.json:/app/service_account.json
    env_file:
      - .env
    environment:
      PG_DB_URL: postgresql://litellm:litellm@postgres:5432/litellm
      REDIS_HOST: redis
      REDIS_PORT: 6379
      PORT: 4000
    command: ["--config", "/app/config.yaml"]

volumes:
  pg_data:
  redis_data:
