version: "3.8"
services:
  mlpa:
    build: .
    image: mlpa:latest
    container_name: mlpa
    platform: linux/amd64
    ports:
      - "8080:8080"
    environment:
      - PG_DB_URL=${PG_DB_URL}
      - MASTER_KEY=${MASTER_KEY}
      - GATEWAY_API_BASE=${GATEWAY_API_BASE}
      - GATEWAY_DB_NAME=${GATEWAY_DB_NAME}
      - CHALLENGE_EXPIRY_SECONDS=${CHALLENGE_EXPIRY_SECONDS}
      - PORT=${PORT}
      - APP_BUNDLE_ID=${APP_BUNDLE_ID}
      - APP_DEVELOPMENT_TEAM=${APP_DEVELOPMENT_TEAM}
      - APP_ATTEST_DB_NAME=${APP_ATTEST_DB_NAME}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - DEBUG=${DEBUG}
      - MODEL_NAME=${MODEL_NAME}
      - TEMPERATURE=${TEMPERATURE}
      - TOP_P=${TOP_P}
