name: Build and Push Docker Image to Google Artifact Registry

on:
  push:
    branches:
      - main
      - feat-use-llm-proxy-prod-artifact-registry

jobs:
  build-and-push:
    environment: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-tags: true
      - name: Create version.json
        run: |
          # create a version.json per
          # https://github.com/mozilla-services/Dockerflow/blob/master/docs/version_object.md
          printf '{"commit":"%s","version":"%s","source":"%s","build":"%s"}\n' \
          "$GITHUB_SHA" \
          "$GITHUB_REF_NAME" \
          "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
          "$GITHUB_SERVER_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID" > version.json
      - name: Debug GCP Variables
        run: |
          echo "GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER: ${{ vars.GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}"
      - name: Build and Tag Container Image
        id: build
        uses: mozilla/deploy-actions/docker-build@e937a559f998239beb7b69ee47200ecf2b9d28c0 # v5.2.0
        with:
          image_name: mlpa
          gar_name: llm-proxy-prod
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Push Container Container Image to GAR
        uses: mozilla-it/deploy-actions/docker-push@e937a559f998239beb7b69ee47200ecf2b9d28c0 # v5.2.0
        with:
          image_tags: ${{ steps.build.outputs.image_tags }}
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          workload_identity_pool_project_number: ${{ vars.GCPV2_WORKLOAD_IDENTITY_POOL_PROJECT_NUMBER }}
