name: linters and unit tests

on:
  pull_request:
    types: [opened, reopened, synchronize, ready_for_review]
  push:
    branches:
      - main

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install uv
        run: pip install uv

      - name: Install requirements
        run: |
          uv pip install -r requirements-dev.txt --system
          uv pip install -r requirements.txt --system
          uv pip install -e . --system

      - name: linters
        run: uv run pre-commit run --all-files --verbose

      - run: pytest src/tests/unit -v
